### ISSUE TITLE
Drozer run app.package.list -- [Errno 0] Error 

### ISSUE THREAD

**Issue by 19oos** [FSecureLABS/drozer#316] opened 2018-01-09 07:29 UTC
### Steps to reproduce
1. Install drozer by win msi 
2. drozer console connect, success
3. run app.package.list, error. 
Here is the result， 
dz> run app.package.list
com.android.cts.priv.ctsshim (com.android.cts.priv.ctsshim)
com.google.android.youtube (YouTube)
com.google.android.ext.services (Android Services Library)
com.android.providers.telephony (鐢佃瘽鍜岀煭淇″瓨鍌?
[Errno 0] Error

### Environment
**Operating system**:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
**Java Version:**
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
**Android Version:**
(LGE Nexus 5X 7.1.2)
**Drozer Version:** 
2.4.4
**Install Method:** Built from source/.deb/.exe/..
win msi
### Drozer Config
```

### Drozer Error Logs

exception in module: IOError: [Errno 0] Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\drozer\console\session.py", line 394, in do_run
    module.run(argv[1:])
  File "C:\Python27\lib\site-packages\drozer\modules\base.py", line 183, in run
    result = self.execute(arguments)
  File "C:\Python27\lib\site-packages\drozer\modules\app\package.py", line 349, in execute
    self.__get_package(arguments, package)
  File "C:\Python27\lib\site-packages\drozer\modules\app\package.py", line 358, in __get_package
    self.stdout.write("%s (%s)\n" % (application.packageName, self.packageManager().getApplicationLabel(application.packageName)))
  File "C:\Python27\lib\site-packages\mwr\common\stream.py", line 58, in write
    self.stream.write(remove_colors(text))
IOError: [Errno 0] Error

**Comment by piaoye0605** [comment] 2018-01-11 22:23
@19oos i want to kown that the problem is resoved?

**Comment by piaoye0605** [comment] 2018-01-11 22:24
@19oos i now happen the same problem

**Comment by 19oos** [comment] 2018-01-14 14:50
@piaoye0605 No.  I reinstalled my windows, then the problem is resolved.

**Comment by lichaolu** [comment] 2018-06-10 14:05
win7 OS is ok,the possible reasons might be permitions of errno 0 in win10 OS.

**Comment by Spr1ngBr0ther** [comment] 2018-10-10 08:21
i now happen the same problem

**Comment by anquanxiaoge** [comment] 2021-01-25 10:24
I also encountered this problem. When I solved the garbled problem of running app.package.list, the [Errno 0] Error error message disappeared.
Link: https://www.jianshu.com/p/dfa92bab3a55

**Comment by JIHOI-KIM** [comment] 2021-02-24 07:47
I found this error is raised by 
___get_package_ function in [modules/app/package.py , Line#351](https://github.com/FSecureLABS/drozer/blob/develop/src/drozer/modules/app/package.py)

It is obvious some packages create **IOError** on Line #358, after getApplicationLabel()'s result is printed.
The simple way to solve it, is just use -n flag(which indicate "do not print application label, but only package name".)

_dz > run app.package.list -n_
![1](https://user-images.githubusercontent.com/57209681/108963963-34679700-76be-11eb-99d4-facda9894624.png)

As you can see from result screen, error is gone.
_For long term solution_, you can revise some codes in module.

Find module's source code from path below(It might be different)
_C:\Python27\Lib\site-packages\drozer\modules\app\pacakge.py_
and add Exception handling code in line #359 as below.

![2](https://user-images.githubusercontent.com/57209681/108964775-44cc4180-76bf-11eb-843f-d7f66f5022b4.png)

Finally you can fix the error into below result.
By exception handling, each **IOError** display Warning, not crashing the sequence.

![3](https://user-images.githubusercontent.com/57209681/108965081-b73d2180-76bf-11eb-9275-70f4ea0ce596.png)

I also created pull request for it. thx.

**Comment by Yogehi** [comment] 2021-02-24 15:21
merged yay

**Closed by Yogehi** 2021-02-24 15:21 UTC
